### ISSUE TITLE
Simple Continuous Delivery pipeline

### ISSUE THREAD

**Issue by edisongustavo** [awslabs/benchmark-ai#306]
We could use AWS CodePipeline to model a simple pipeline so we can have continuous deployment.

# Tasks:

- [x] Pipeline that builds the `master` branch: Use Terraform: PR #315 
- [x] Make `master` CodeBuild jobs publish the deployment yaml files as artifacts: PR https://github.com/MXNetEdge/benchmark-ai/pull/333
- [x] Add CodePipeline step that deploys the yaml artifacts from the `master` CodeBuild jobs. PR: https://github.com/MXNetEdge/benchmark-ai/pull/338/
- [x] Make `master` CodeBuild jobs publish docker images to dockerhub (or ECR): PR: https://github.com/MXNetEdge/benchmark-ai/pull/342
- [x] Add CodePipeline step that runs "blackbox" tests using the `bai` CLI.

**IMPORTANT**: These tasks do not involve doing CD for the infrastructure, this is still manual
